set number 
set showmatch  
set autoindent  
set cindent  
set shiftwidth=4  
set smartindent  
set smarttab  
set softtabstop=4  
set backspace=indent,eol,start  
set visualbell  
set hlsearch  
set incsearch  
set ruler  
set undolevels=1000  
syntax on  
